version: "3.9"

services:

        basex:
                image: basex/basexhttp:9.4.6
                ports:
                        - 8080:8984
                volumes:
                        - "${DATA_DIR}/basex/data:/srv/basex/data"
                        - "${DATA_DIR}/basex/webapp:/srv/basex/webapp"
        fuseki:
                image: secoresearch/fuseki:latest
                environment:
                        ENABLE_DATA_WRITE: true
                        ENABLE_UPDATE: true
                        ENABLE_UPLOAD: true 
                ports:
                        - 3030:3030
                volumes:
                        - "${DATA_DIR}/fuseki/fuseki-data:/fuseki-base/databases"
                        - "${DATA_DIR}/fuseki/fuseki-configuration:/fuseki-base/configuration"
